config/routes.rb
Alexis::Application.routes.draw do
  
  root :to => 'home#index'
  
  resources :users
    match 'signup' => 'users#new'
    
  resources :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    
  resources :business_cards do
    
    member do
      post :select_theme
      post :set_background_color
      post :order_contact_info
      get :stats
      get :delete
    end
    
    resources :business_card_section_orders do
      collection do
        post :update
      end
    end
    
  end
  
  
  
  resources :profiles, :only => [:show, :edit, :update]
  
  namespace :backbone do
    resources :business_cards
    resources :themes, :only => [:index]
    resources :background_colors, :only => [:index]
  end
  
  match '/stage' => 'stage#index'
    
  match '/dashboard' => 'dashboard#index'
  
  match '/:url' => 'business_cards#show'
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :require_user
  
  def index
    
    @business_cards = current_user.business_cards
    
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%
@title_for_layout = 'Dashboard'
@body_id = 'dashboard'
%>

<h1 class="header">My cards</h1>

<%= render :partial => 'shared/flash_notice' %>

<div id="mycards" class="vanilla_region">
  
  <div class="white_region">
    <div class="beige_region">
  
      <% if @business_cards.count > 0 %>
    
    
            <ul id="mycards_list" class="item_list">
              <% @business_cards.each do |business_card| %>
                <li class="clearfix">
                  <div class="left">
                    <a class="card_name tooltip" href="/<%= business_card.url %>" title="View this card (in a new tab)"><%= business_card.title %></a>
                    <div class="card_last_updated">Last updated on <%= convert_timestamp_to_date business_card.updated_at  %></div>
                  </div>
                  <div class="options">
                    <a class="delete action_link tooltip" href="/business_cards/<%= business_card.id %>/delete" title="Delete"></a>
                    <a target="_blank" href="/<%= business_card.url %>" class="viewlive action_link tooltip" title="View this card"><%= business_card.url %></a>
                    <%= link_to 'Edit', edit_business_card_path(business_card), :class => 'edit action_link tooltip', :title => 'Edit this card' %>
                    <%= link_to 'Analytics', stats_business_card_path(business_card), :class => 'analytic action_link', :title => 'View stats' %>
                  </div>
                </li>
              <% end %>
            </ul>
        
            <%= link_to 'Create new card', new_business_card_path, :class => 'red_btn' %>
        
      <% else %>
        <p style="margin-bottom:10px">You have yet created any cards. </p> 
        <%= link_to 'Create one now', new_business_card_path, :class => 'red_btn' %>
      <% end %>
  
    </div>
  </div>
  
</div>