config/routes.rb
Alexis::Application.routes.draw do
  
  root :to => 'home#index'
  
  resources :users
    match 'signup' => 'users#new'
    
  resources :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    
  resources :business_cards do
    
    member do
      post :select_theme
      post :set_background_color
      post :order_contact_info
      get :stats
      get :delete
    end
    
    resources :business_card_section_orders do
      collection do
        post :update
      end
    end
    
  end
  
  
  
  resources :profiles, :only => [:show, :edit, :update]
  
  namespace :backbone do
    resources :business_cards
    resources :themes, :only => [:index]
    resources :background_colors, :only => [:index]
  end
  
  match '/stage' => 'stage#index'
    
  match '/dashboard' => 'dashboard#index'
  
  match '/:url' => 'business_cards#show'
  
end

app/models/background.rb
class Background < ActiveRecord::Base
end

app/models/background_color.rb
class BackgroundColor < ActiveRecord::Base
end

app/models/business_card.rb
class BusinessCard < ActiveRecord::Base
  
  # associations
  belongs_to :user
  has_one :business_card_theme, :dependent => :destroy
  has_one :business_card_background, :dependent => :destroy
  has_one :business_card_information, :dependent => :destroy
  has_many :business_card_section_orders, :dependent => :destroy, :order => 'weight DESC'
  has_many :visitor_infos, :dependent => :destroy
  
  accepts_nested_attributes_for :business_card_information
  
  # validations
  validates_presence_of :url, :message => ' is required'
  validates_uniqueness_of :url, :message => ' is not available'
  validates_presence_of :title, :message => ' is required'
  
  def as_json(args={})
    super(:methods => :formatted_created_at, :except => :date)
  end
  
  def formatted_created_at
    self.created_at.strftime("%b %d, %Y")
  end
    
end

app/models/business_card_theme.rb
class BusinessCardTheme < ActiveRecord::Base
  
  belongs_to :business_card
  
  def self.create_business_card_theme(business_card)
    
    default_theme = Theme.get_default_theme
    
    business_card.business_card_theme = BusinessCardTheme.new(:theme_id => default_theme.id)
    business_card.business_card_theme.save
  end
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  
  def self.get_default_theme
    
    default_theme = Theme.where(:default => true, :status => :active).first
    
    if default_theme.nil?
      default_theme = Theme.first
    end
      
    default_theme
    
  end
  
  def self.theme_applicable(theme_id)
    theme = Theme.where(:id => theme_id, :status => :active).first
    !theme.nil?
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Gravtastic
  gravtastic :size => 120
  
  has_one :profile, :dependent => :destroy
  has_many :business_cards, :dependent => :destroy, :order => 'created_at DESC'
  
  attr_accessor :first_name, :last_name
  
  validates_presence_of :first_name, :message => ' is required'
  validates_presence_of :last_name, :message => ' is required'
  validates_length_of :username, :minimum => 4, :message => ' is too short (must be at least 4 characters)'
  validates_uniqueness_of :username, :message => ' is not available', :case_sensitive => false
  validates :email, :email => {:message => ' is not valid'}
  validates_uniqueness_of :email, :message => ' is already in use', :case_sensitive => false
  validates_length_of :password, :minimum => 4, :maximum => 10, :message => ' is too short (must be between 4 and 10 characters)'
  
  acts_as_authentic do |config|
     config.crypto_provider = Authlogic::CryptoProviders::MD5
     config.validate_email_field = false
     config.validate_login_field = false
     config.validate_password_field = false
     config.login_field = :email
     config.validate_login_field = false
  end
  
  before_save :downcase
  
  private
  
  def downcase
    self.username = self.username.downcase
    self.email = self.email.downcase
  end
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/models/visitor_info.rb
class VisitorInfo < ActiveRecord::Base
  
  include GeoKit::Geocoders
  
  def self.update_analytics(business_card, request, geo_location)
    user_agent = UserAgent.parse(request.user_agent)
    
    if user_agent[0].product == 'Opera'
      browser = 'Opera'
    elsif !user_agent[2].nil? && user_agent[2].product == 'Chrome'
      browser = 'Chrome'
    elsif !user_agent[3].nil? && user_agent[3].product == 'Safari'
      browser = 'Safari'
    else
      browser = user_agent[2].product
    end
    
    location = IpGeocoder.geocode('12.215.42.19')
    
    business_card.visitor_infos.create(
      :browser => browser,
      :version => user_agent.version,
      :platform => user_agent[0].comment.join(" "),
      :ip_address => request.remote_addr, 
      :domain_name => request.host,
      :province => geo_location.province,
      :state => geo_location.state,
      :country_code => geo_location.country_code,
      :zip => geo_location.zip,
      :city => geo_location.city
    )
  end
  
  def self.get_browser_stats_by_business_card(business_card)
    self.where(:business_card_id => business_card.id).find(:all)
  end
  
  def self.get_browser_stats(visitor_infos)
    browsers = {}
    
    for info in visitor_infos
      if browsers.has_key?(info.browser)
        browsers[info.browser] += 1
      else
        browsers[info.browser] = 1
      end
    end
    
    browsers
  end
  
  def self.get_browser_version_stats(visitor_infos)
    versions = {}
    
    for info in visitor_infos
      if !versions.has_key?(info.browser)
        versions[info.browser] = {}  
      end
      
      if !versions[info.browser].has_key?(info.version)
        versions[info.browser][info.version] = 1
      else
        versions[info.browser][info.version] += 1
      end
      
    end
    
    versions
  end
  
  def self.get_platform_stats(visitor_infos)
    platforms = {}
    
    for info in visitor_infos
      if platforms.has_key?(info.platform)
        platforms[info.platform] += 1
      else
        platforms[info.platform] = 1
      end
    end
    
    platforms
  end
  
  def self.get_country_stats(visitor_infos)
    countries = {}
    
    for info in visitor_infos
      if countries.has_key?(info.country_code)
        countries[info.country_code] += 1
      else
        countries[info.country_code] = 1
      end
    end
    
    countries
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :redirect
  
  def index
    render :layout => "signup"
  end
  
  private 
  
  def redirect
    redirect_to dashboard_path unless !logged_in?
  end
  
end

app/controllers/stage_controller.rb
class StageController < ApplicationController
  
  before_filter :require_user
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/email_helper.rb
module EmailHelper
  
  
  def string_to_ascii(string)
		
		asciiString = "";

		string.each_byte do |c|
		  asciiString += "&##{c};"
	  end

		asciiString
	end
	
	def obfuscate_email(email)
	  
		email_obfuscated = string_to_ascii(email)
		
		email_obfuscated = '<script type="text\/javascript">document.write("<a hr"+"ef=&#109;&#97;&#105;&#108;&#116;&#111;&#58;");document.write("' + email_obfuscated + '>' + email_obfuscated + '<\/a>");</script>'
	
    email_obfuscated.html_safe
	end
  
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  
  def generate_profile_location(profile)
    location = []
    
    location << profile.city unless profile.city.blank?
    location << profile.state unless profile.state.blank?
    location << profile.country unless profile.country.blank?
    
    location.join(', ')
    
  end
  
end

app/helpers/stage_helper.rb
module StageHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title_for_layout %> - Alexis</title>
  <%= stylesheet_link_tag [
    'master',
    ] %>
  <%= javascript_include_tag [
    'jquery',
    'jquery.tooltip',
    'jquery-ui-1.8.5.custom.min.js',
    'master.jscrambler',
    ] %>
  <%= csrf_meta_tag %>
</head>
<body id="<%= @body_id %>">
  
<%= render :partial => 'shared/alert' %>

<%= render :partial => 'shared/taskbar' %>

<div id="stage">
  <%= yield %>
</div>

<div id="overlay"></div>

</body>
</html>

app/views/layouts/business_card.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title_for_layout %> - Alexis</title>
  <meta name="description" content="<%= @business_card.title %>" />
  <%= stylesheet_link_tag ['business_card', "themes/#{@theme.slug}"] %>
  <%= javascript_include_tag [
    'jquery',
    'jquery.hoverIntent',
    'business_card',
  ] %>
  <%= csrf_meta_tag %>
  
  <% if @body_id == 'show_business_card' %>
  <style>
    body {
      <% if (@business_card.business_card_background.which == 'color') %>
        background:#<%= @business_card.business_card_background.background_color %>;
      <% end %>
    }
  </style>
  <% end %>
</head>
<body id="<%= @body_id %>">

<%= yield %>

</body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title_for_layout %> - Alexis</title>
  <%= stylesheet_link_tag [
    'master'
    ] %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id="<%= @body_id %>">

<%= yield %>

</body>
</html>

app/views/layouts/stage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title_for_layout %> - Alexis</title>
  <%= stylesheet_link_tag [
    'master',
    ] %>
  <%= javascript_include_tag [
    'jquery',
    'json2',
    'underscore',
    'backbone',
    'backbone/application',
    'backbone/controllers/business_cards',
    'backbone/models/business_card',
    'backbone/collections/business_cards',
    'backbone/views/index',
    'backbone/views/new',
    'backbone/views/edit',
    'backbone/views/errors',
    'backbone/views/success',
    'stage'
    ] %>
  <%= include_javascripts :app %>
  <%= csrf_meta_tag %>
  <script>
    $(function(){
      App.init();
      
      Alexis.init();
    })
  </script>
</head>
<body id="<%= @body_id %>">
  
<%= render :partial => 'shared/alert' %>

<%= render :partial => 'shared/taskbar' %>

<div id="stage">
  <%= yield %>
</div>

<div id="overlay"></div>

</body>
</html>

app/views/shared/_alert.html.erb
<div id="alert" style="display:none"></div>

app/views/shared/_background_gallery.html.erb
<div id="background_gallery" class="gallery" style="display:none">
  <%= image_tag 'closeOverlay.png', :class => :close_overlay %>
  <div id="background_gallery_inner" class="gallery_inner">
    <h2><%= image_tag 'backgroundColor.png', :alt => 'Background color' %></h2>
    <div id="color_pallete" class="clearfix">
      <% @background_colors.each do |color| %>
        <div id="<%= color.hex_value %>" class="color_choice" style="background: #<%= color.hex_value %>">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_business_card_section_modal.html.erb
<div id="business_card_section_modal" class="overlay_modal" style="display:none">
  <h3>Order Contact Information</h3>
  <%= image_tag 'closeOverlay.png', :class => :close_overlay, :id => :close_business_card_section_modal %>
  <div class="sortable ui-sortable">
    <% @section_order.each do |section| %>
      <div id="section_<%= section.id %>" class="section">
        <%= section.name %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_card_owner_profile.html.erb
<% if !@profile.hidden %>

<span id="profile">Profile</span>
<div id="profile_leaf">
  <%= image_tag 'arrowTip.png', :id => :profile_leaf_tip %>
  <div id="profile_leaf_inner" class="clearfix">
      
      <%= image_tag @profile.user.gravatar_url, :id => :profile_photo %>
      
      <div id="profile_details">
        <p id="profile_name"><%= @profile.first_name %> <%= @profile.last_name %></p>
        <%= "<p>#{@profile.job_title}</p>".html_safe unless @profile.job_title.blank? %>
      
        <% location = generate_profile_location @profile %>
        <%= "<p>#{location}</p>".html_safe unless location.blank? %>
      
        <%= "<p><a href=\"#{@profile.website}\" target=\"_blank\">#{@profile.website}</a></p>".html_safe unless @profile.website.blank? %>
        
        <%= "<p id=\"profile_about\">#{@profile.about_me}</p>".html_safe unless @profile.about_me.blank? %>
        
        <ul id="social_networks">
          <li>
            <% if !@profile.facebook.blank? %>
              <a href="<%= @profile.facebook %>" target="_blank"><%= image_tag 'facebook_16.png', :alt => 'Facebook', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.twitter.blank? %>
              <a href="<%= @profile.twitter %>" target="_blank"><%= image_tag 'twitter_16.png', :alt => 'Twitter', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.flickr.blank? %>
              <a href="<%= @profile.flickr %>" target="_blank"><%= image_tag 'flickr_16.png', :alt => 'Facebook', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.linked_in.blank? %>
              <a href="<%= @profile.linked_in %>" target="_blank"><%= image_tag 'linkedin_16.png', :alt => 'LinkedIn', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.dribble.blank? %>
            <a href="<%= @profile.dribble %>" target="_blank"><%= image_tag 'dribbble_16.png', :alt => 'Dribble', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.gowalla.blank? %>
              <a href="<%= @profile.gowalla %>" target="_blank"><%= image_tag 'gowalla_16.png', :alt => 'Gowalla', :class => :network_icon %></a>
            <% end %>
            <% if !@profile.forrst.blank? %>
              <a href="<%= @profile.forrst %>" target="_blank"><%= image_tag 'forrst_16.png', :alt => 'Forrst', :class => :network_icon %></a>
            <% end %>
          </li>
        </ul>
      </div>
  </div>
</div>

<% end %>

app/views/shared/_flash_notice.html.erb
<% if flash[:notice] %>
<div class="result_success">
  <%= flash[:notice] %>
</div>
<% end %>

app/views/shared/_form_errors.html.erb
<div class="result_error"><%= f.error_messages :header_message => "", :message => "" %></div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  
</div>

app/views/shared/_taskbar.html.erb
<div id="taskbar">
  <%= image_tag 'alexis.png', :alt => 'Alexis', :id => 'alexis' %>
  <div id="taskbar_nav">
    <%= image_tag current_user.gravatar_url, :class => :user_image, :id => :taskbar_user_image %>
    <ul id="global_top_nav">
      <li>Logged in as <%= current_user.profile.first_name %> <%= current_user.profile.last_name %></span></li>
      <li><%= link_to 'Edit profile', edit_profile_path(current_user.profile) %></li>
      <li><%= link_to 'My cards', dashboard_path %></li>
      <li class="last"><%= link_to 'Logout', logout_url %></li>
    </ul>
  </div>
  <div class="clearfloat"></div>
</div>
<div id="taskbar_divider"></div>

app/views/shared/_theme_gallery.html.erb
<div id="theme_gallery" class="gallery" style="display:none">
  <%= image_tag 'closeOverlay.png', :class => :close_overlay %>
  <div id="theme_gallery_inner" class="gallery_inner">
    <h2><%= image_tag 'selectTheme.png', :alt => 'Select a theme' %></h2>
    <% @themes.each do |theme| %>
      <%= image_tag "themes_gallery/#{theme.slug}.jpg", :class => 'theme_preview tooltip', :title => theme.title, :rel => theme.id %>
    <% end %>
  </div>
  <div id="theme_gallery_message" style="margin-bottom:0; display:none"></div>
</div>